### ISSUE TITLE
test_pp fails

### ISSUE THREAD

**Issue by 1gn1t10n** [relic-toolkit/relic#7]
**System**: Debian Jessie (x86-64)
**RELIC version**: git (2015-01-19)
**Configuration**: `-DARITH=gmp -DALLOC=DYNAMIC -DBN_PRECI=8192 -DFP_PRIME=1536`

---

The unit test for the PP module fails for the 1536-bits supersingular curve bundled with RELIC (SS-P1536): `Testing if weil pairing is bilinear... [FAIL]` at `relic.git/test/test_pp.c:356`.

The test passes for other non-supersingular curves like BN-P158, BN-P254, B12-P638.

I have also tried with one of my own supersingular curves and the test fails sooner at `Testing if miller doubling is correct...` in `test_pp.c:191`. I believe I set the parameters correctly, as `test_ep` works.

**Comment by dfaranha** [comment]
Thanks for reporting! This is broken for a long time, but was finally fixed in the repository. Can you please check?

**Comment by 1gn1t10n** [comment]
Hi Diego! Thank you for the quick patch. Indeed, it fixed test_pp. Now it works for SS-P1536 as well.

However, for my curve I still have the doubling problem in `doubling2` (`test_pp.c:189`) :( . I think `ep_dbl` is correct, I checked it with PARI/GP. The problem must be in `pp_dbl_k2_projc_basic`. I'll do more debugging and maybe open another issue.

**Comment by dfaranha** [comment]
I can also do some testing if you don't mind sharing the curve parameters. :)

**Comment by 1gn1t10n** [comment]
Yes, please!
`a = 0; b = 1; n = 11044283; P = 66265697; h = 6; g = [123776, 2599299];`
They are in base 10.

The test picks a q at random. But let's fix
`q = [57930974, 18303335]; qq = [843167, 5273927]`
or in hex
`q = [373F4DE, 1174967]` `qq = [CDD9F, 507947]`
Where qq is the double of q, ie `q+q`.

`ep_dbl` works, but `pp_dbl_k2_projc_basic` gives something different.

**Comment by dfaranha** [comment]
I think the current pairing code only supports curves with `p = 3 mod 4`. We would need to tweak the formulas to allow other choices of prime.

**Comment by 1gn1t10n** [comment]
The implementation of `pp_dbl_k2_projc_basic` references [this doubling formula](http://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-3.html#doubling-dbl-2001-b). Unlike other doubling formulas on that page, it doesn't have any assumptions listed.

Or are you referring to other code along the execution path? The `fp` module seemed to work fine without specific primes. Although I think I might recall a problem with `fp_dbl` at some point. I'll have to check.

**Comment by dfaranha** [comment]
The doubling is probably fine, but the distortion map formula depends on the choice of prime, so the issue is probably there. Can you check if `test_fpx` gets past the quadratic extension tests?

**Comment by 1gn1t10n** [comment]
Thanks for the insight. Indeed, `test_fpx` fails.

So for the curve with `P = 66265697`, it fails at `Testing if reading and writing a finite field element are consistent...`. Actually it crashes with `relic.git/src/fpx/relic_fpx_util.c,108: insufficient buffer capacity`.

I took a different curve with `P = 3 mod 4`: `a = 0; b = 1; n = 12557141; P = 301371383; h = 24; g = [8, 7811483];`
This time `test_fpx` goes further to `Testing if frobenius and exponentiation are consistent...` (in the sextic extension). So the quadratic extension tests work, but `test_pp` fails as before at the Miller doubling. 

I wanted to note that the `test_fpx` of the vanilla library does not work completely for `FP-PRIME=1536`. As above, it stops at "frobenius" (in sextic extension). However, `test_pp` *does* work (with your recent patches).

:(

**Comment by dfaranha** [comment]
I will have to take a look on these issues, but let me say that these parameters do not necessarily work for extensions higher than quadratic. For efficiency purposes, RELIC only supports certain towering choices hard-coded in the library. That's the price we pay for speed. :(

**Comment by 1gn1t10n** [comment]
It would be nice if you could take a look. Unfortunately, I don't understand the theory very well. I was expecting to just take the bilinear map as a black box and play with it.

**Comment by 1gn1t10n** [comment]
You mentioned at some point that:
> The doubling is probably fine, but the distortion map formula depends on the choice of prime, so the issue is probably there. Can you check if test_fpx gets past the quadratic extension tests?

I checked the doubling algorithm, it works as intended. The elephant in the room is listed at the top of the [doubling formula page](http://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-3.html): there is an assumption for all those algorithms that `a = -3` (the curve parameter in the Weierstrass equation). In my case `a = 0`.

However, I remember `EP_ADD = BASIC`  didn't work either, which seemed strange. I'll have a look at it again.

I was confused for a while by the name "*_projc_*". The implementation uses Jacobian coordinates, not projective, right? (http://en.wikipedia.org/wiki/Elliptic_curve_cryptography#Projective_coordinates)

**Comment by dfaranha** [comment]
I took another look, but could not fully reproduce your issues. Can you give more details on how you configured the library for such a small prime? Thanks!

PS: The implementation uses Jacobian projective coordinates, and we have formulas for both a = 0 and a = -3 (check OPT_MINUS3 and OPT_ZERO).

**Comment by 1gn1t10n** [comment]
I configured the library with `cmake -DDEBUG=on -DBENCH=10 -DTESTS=10 -DARITH=gmp -DALLOC=DYNAMIC -DBN_PRECI=8192 -DFP_PRIME=32` . However, I get the same problem when testing with bigger `P = 3 mod 4` (~1024 bits)

You are right about OPT_ZERO. Unfortunately, there are multiple places where the doubling formulas are implemented (`relic_ep_dbl.c` and `relic_pp_dbl.c`) and not all of them use OPT_ZERO.

Let's look at [`doubling2`](https://github.com/relic-toolkit/relic/blob/master/test/test_pp.c#L185) where the problem manifests itself. The following code gets called:
`pp_dbl_k2` → `pp_dbl_k2_projc` → `pp_dbl_k2_projc_lazyr` which implements only [dbl-2001-b](http://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-3.html#doubling-dbl-2001-b) without checking for the parameter `a` first. This is where the doubling error comes from.
As a side note, it looks like [`pp_dbl_k2_projc_basic`](https://github.com/relic-toolkit/relic/blob/master/src/pp/relic_pp_dbl.c#L108) and [`pp_dbl_k2_projc_lazyr`](https://github.com/relic-toolkit/relic/blob/master/src/pp/relic_pp_dbl.c#L347) are identical except for the name and one comment line. Is this intentional?

Next, the above result is compared to `ep_dbl`. The code that gets called is:
`ep_dbl` → `ep_dbl_projc` → [`ep_dbl_projc_imp`](https://github.com/relic-toolkit/relic/blob/master/src/ep/relic_ep_dbl.c#L188). This one works, it has the formula for `a = 0`.

The workaround that I found was to override `pp_dbl_k2` with `pp_dbl_k2_basic` which calls `ep_dbl_slp_basic` → `ep_dbl_basic_imp`. This seems to work and clears the test for "miller doubling".
Skipping the test for "miller doubling in projective coordinates" (which calls specifically the problematic `pp_dbl_k2_projc`), the test stops again at "pairing is bilinear" (Tate by default).

And here I cannot even test with PARI/GP. I don't understand what the mapping is supposed to return. From what I see in RELIC, it's an element of F_p^2 (basically two elements of F_p judging from how `fp2_t` is defined). However, in PARI/GP the `elltatepairing` functions returns an element of F_p from what I can see.

More succintly:
* `pp_dbl_k2_projc_lazyr` implements doubling code only for `a = -3` without verifying.
* `pp_dbl_k2_projc_lazyr` and `pp_dbl_k2_projc_basic` are the same
* how to verify the result of the Tate pairing against a different algebra program (ie: PARI/GP)

**Comment by dfaranha** [comment]
About these issues:
* We do not have general formulas for pairing computation, only for the curves we need, in an attempt to save code size in smaller platforms RELIC also supports.
* Now these are not the same anymore, as I implemented some lazy reduction speedups.
* You need to check if PARI/GP returns a compressed pairing element. If that is the case, you should see the PARI/GP result as the first component of the RELIC Fp^2 result. In general, this is not mandatory, since some performance improvements can change the pairing result without affecting its bilinearity.
